import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from "@/components/Header"
import About from "@/components/About"
import SectionHeader from "@/components/SectionHeader";
import FeaturedCard from "@/components/FeaturedCard";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CHANKO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
            <div className={styles.headerContainer}>
                <span className={styles.title}>
                    <h3>Eric Chang</h3>
                </span>
                <span className={styles.description}>
                    Software Developer - Data Analyst
                </span>
            </div>
            <div className={styles.mainGrid}>

                 <section className={styles.featured}>
                     <div className={styles.featuredContent}>
                         <h3>About Me</h3>
                         <div></div>
                         <img className={styles.portrait} src="/me.jpeg"/>
                     </div>

                </section>

                <button className={styles.projects}>
                    <h1>Projects</h1>
                </button>
                <section className={styles.photography}>

                </section>
            </div>
            <section className={styles.timeline}>

            </section>
            <Footer className={styles.footer} />
        </main>

    </>
  )
}
