import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ChankoLogo from "@/components/ChankoLogo";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <nav id="nav" className={styles.navBar}>

            <ul>
                <li><a href='#' className={styles.chankoLogo}>
                <ChankoLogo/>
            </a></li>
                <li><a href='#' className={styles.navBarList}>About me</a></li>
                <li><a href='#' className={styles.navBarList}>Projects</a></li>
                <li><a href='#' className={styles.navBarList}>Articles</a></li>
                <li><a href='#' className={styles.navBarList}>Contact</a></li>
            </ul>

        </nav>
      <main className={styles.main}>

      </main>
    </>
  )
}
